http {
    # Настройка upstream для балансировки нагрузки
    upstream backend_servers {
        server backend1.example.com;
        server backend2.example.com;
        server backend3.example.com;
    }

    # Зона для хранения состояния лимита запросов по IP клиента.
    # 10 запросов в минуту = ~0.17 запроса в секунду
    limit_req_zone $binary_remote_addr zone=partner_limit:10m rate=10r/m;

    # Свой код ответа при превышении лимита, чтобы отдавать 429 вместо 503 по умолчанию
    limit_req_status 429;

    server {
        listen 80;

        location / {
            limit_req zone=partner_limit burst=5 nodelay;
            proxy_pass http://backend_servers;
        }

    }
}
